/** Auto-generated by scripts/sync-production-csp.mjs — do not edit manually */
export const PRODUCTION_SCRIPT_HASHES: string[] = [
  "/jNJv/AN/c1ykkH7pteAz8Mf+1S4auR73xrZVm7l32s=",
  "51zf2RU9uS47lJQZpG1HuOB9tziLfEcUGfOpDpKGXgo=",
  "5B1Vxj50ahQdwOretbt0Mfx8vAL4FUYYf/rPxvvrL7I=",
  "6byV3oQegwYXtv/74TO8TX3Rm50W5EiZYOFS02N9pWE=",
  "BO6vAOq81ZrAMG9jLLS8VLDPTjFAjq0XxAunPtE/4V0=",
  "IC9Fgg1OC+fg4ROXqHyXveHYNha9jBVc1LUAZiO/0uk=",
  "Q8kuVX9ppHEFhgsdzpry5GaXW0qBS13JYRmGWjyeWho=",
  "ToFtGsSVSxl2rU7iBUyjmi6CyrtvVmBdtYGKsZtYUEc=",
  "X9eIjgTKZTU0kizuIjltl3oc417ZFRy0bm2F1UenIxc=",
  "a+D2WcT3yMLtMRgf1FLTObfiywi7TZ9rDGUk8oZIQfA=",
  "goZpX5BJsDuzl+yngL7IRk0UuvXTuBZLygE2qOaLKgE=",
  "speQlqFpG2f1qppsQY8BGaF8u6cZwkIrpHNAmzYDZLs="
];

export const PRODUCTION_WORKER_HASHES: string[] = [
  "Q3l9b1pZYUvj0imh8y3GmpQQF/xjbOekVSRZNcxn6dI="
];

export const PRODUCTION_CONTENT_SECURITY_POLICY = "default-src 'self'; script-src 'sha256-/jNJv/AN/c1ykkH7pteAz8Mf+1S4auR73xrZVm7l32s=' 'sha256-51zf2RU9uS47lJQZpG1HuOB9tziLfEcUGfOpDpKGXgo=' 'sha256-5B1Vxj50ahQdwOretbt0Mfx8vAL4FUYYf/rPxvvrL7I=' 'sha256-6byV3oQegwYXtv/74TO8TX3Rm50W5EiZYOFS02N9pWE=' 'sha256-BO6vAOq81ZrAMG9jLLS8VLDPTjFAjq0XxAunPtE/4V0=' 'sha256-IC9Fgg1OC+fg4ROXqHyXveHYNha9jBVc1LUAZiO/0uk=' 'sha256-Q8kuVX9ppHEFhgsdzpry5GaXW0qBS13JYRmGWjyeWho=' 'sha256-ToFtGsSVSxl2rU7iBUyjmi6CyrtvVmBdtYGKsZtYUEc=' 'sha256-X9eIjgTKZTU0kizuIjltl3oc417ZFRy0bm2F1UenIxc=' 'sha256-a+D2WcT3yMLtMRgf1FLTObfiywi7TZ9rDGUk8oZIQfA=' 'sha256-goZpX5BJsDuzl+yngL7IRk0UuvXTuBZLygE2qOaLKgE=' 'sha256-speQlqFpG2f1qppsQY8BGaF8u6cZwkIrpHNAmzYDZLs='; style-src 'self' https://fonts.googleapis.com; style-src-attr 'unsafe-inline'; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; worker-src 'sha256-Q3l9b1pZYUvj0imh8y3GmpQQF/xjbOekVSRZNcxn6dI='; manifest-src 'self'; object-src 'none'; base-uri 'self'; frame-src 'none'; frame-ancestors 'none'; form-action 'self'";
